#!/usr/bin/env python3
"""Tooling for agent knowledge bases (agent-knowledge-template).

Standard library only, Python >= 3.11. Usage:

    python .knowledge-base/manage.py <command> [--help]

Commands: index, lint, new-topic, install, init, embed, upgrade, check-template, can-auto-merge.
"""

from __future__ import annotations

import sys

if sys.version_info < (3, 11):
    sys.exit("Python >= 3.11 is required (found %d.%d)." % sys.version_info[:2])

import argparse
import json
import os
import re
import shutil
import subprocess
import tomllib
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = "knowledge-base.toml"
TEMPLATE_FILE = ".knowledge-base/template.toml"
MIGRATIONS_FILE = ".knowledge-base/MIGRATIONS.md"
GUIDE_FILE = "AGENTS.md"
TOPICS_DIR = "topics"
INDEX_FILE = "index.md"
EXAMPLE_TOPIC = "example"

INDEX_COMMAND = "python .knowledge-base/manage.py index"
ROOT_INDEX_NOTICE = f"<!-- Generated by `{INDEX_COMMAND}`. Do not edit. -->"
BEGIN_MARKER = f"<!-- BEGIN GENERATED CONTENTS: do not edit, run `{INDEX_COMMAND}` -->"
BEGIN_PREFIX = "<!-- BEGIN GENERATED CONTENTS"
END_MARKER = "<!-- END GENERATED CONTENTS -->"

CONTRIBUTION_MODES = ("pull-request", "direct-push", "with-project")
DEFAULT_CONTRIBUTION = "pull-request"
VERSION_TAG_RE = re.compile(r"refs/tags/v(\d+\.\d+\.\d+)")

FRONTMATTER_KEYS = ("title", "description")
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")
FILE_LINES_WARN, FILE_LINES_MAX = 300, 500
INDEX_LINES_WARN = 80
DESCRIPTION_CHARS_WARN = 200
# A pull request is merged automatically only if every changed path starts with one of these.
AUTO_MERGE_PATHS = (f"{TOPICS_DIR}/", INDEX_FILE)
SKIP_DIRS = {".git", "__pycache__", "node_modules"}
# Files `install` keeps when the target already has them (e.g. created with a new repository).
KEEP_IF_EXISTS = {"LICENSE", ".gitignore", ".gitattributes"}

SECRET_PATTERNS = {
    "GitHub token": re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{40,})"),
    "AWS access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private key": re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    "Slack token": re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}"),
    "API key": re.compile(r"\bsk-(?:ant-|proj-)?[A-Za-z0-9_-]{32,}"),
}

STRIP_RE = re.compile(r"^[ \t]*(```|~~~)[^\n]*\n.*?^[ \t]*\1[^\n]*$|<!--.*?-->|`[^`\n]*`", re.M | re.S)
LINK_RE = re.compile(r"\[[^\]\n]*\]\(\s*<?([^)\s>]*)>?(?:\s+[\"'][^\"'\n]*[\"'])?\s*\)")
YAML_SPECIAL_START = tuple("[]{}&*!|>%@`\"'#?")


# --- helpers -----------------------------------------------------------------


def rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def load_config() -> dict:
    path = ROOT / CONFIG_FILE
    if not path.is_file():
        fail(f"{CONFIG_FILE} not found in {ROOT}")
    return load_toml(path)


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def parse_version(version: str) -> tuple[int, ...]:
    if not VERSION_RE.match(str(version)):
        raise ValueError(f"invalid version {version!r}, expected MAJOR.MINOR.PATCH")
    return tuple(int(part) for part in version.split("."))


def github_slug(url: str) -> str | None:
    """Return 'owner/repo' for a GitHub HTTPS or SSH URL."""
    m = re.search(r"github\.com[:/]+([^/\s]+)/([^/\s]+?)(?:\.git)?/?$", url or "")
    return f"{m[1]}/{m[2]}" if m else None


def git(*args: str, cwd: Path = ROOT) -> str:
    # Never wait for credential prompts: agents and CI cannot answer them.
    env = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}
    result = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, encoding="utf-8", env=env)
    if result.returncode != 0:
        fail(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def git_toplevel(path: Path) -> Path | None:
    """Root of the git working tree containing `path` (which may not exist yet)."""
    probe = path.resolve()
    while not probe.exists():
        probe = probe.parent
    result = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=probe, capture_output=True, text=True)
    top = result.stdout.strip()
    return Path(top).resolve() if result.returncode == 0 and top else None


def is_embedded(root: Path) -> bool:
    """True if the knowledge base is a folder inside a larger repository, e.g. a project."""
    top = git_toplevel(root)
    return top is not None and top != root.resolve()


def set_github_output(**values: str) -> None:
    """Expose values as step outputs when running in GitHub Actions."""
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a", encoding="utf-8") as f:
            for key, value in values.items():
                f.write(f"{key}={value}\n")


def yaml_value(value: str) -> str:
    if value.startswith(YAML_SPECIAL_START) or ": " in value or " #" in value or value.endswith(":"):
        return json.dumps(value, ensure_ascii=False)
    return value


def is_skipped(relpath: Path) -> bool:
    return any(part.startswith(".") or part in SKIP_DIRS for part in relpath.parts)


def guide_link(folder: Path) -> str:
    return Path(os.path.relpath(ROOT / GUIDE_FILE, folder)).as_posix()


# --- frontmatter -------------------------------------------------------------


def parse_frontmatter(text: str) -> tuple[dict[str, str] | None, list[str]]:
    """Parse the supported YAML subset: single-line `key: value` pairs. Returns (fields, problems)."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None, ["missing frontmatter: file must start with '---'"]
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return None, ["frontmatter is not closed with '---'"]
    fields: dict[str, str] = {}
    problems: list[str] = []
    for line in lines[1:end]:
        if not line.strip():
            continue
        m = re.fullmatch(r"([A-Za-z_][\w-]*):(?:\s+(.*))?", line.rstrip())
        if not m:
            problems.append(f"unsupported frontmatter line {line.strip()!r}: use single-line 'key: value'")
            continue
        key, value = m[1], (m[2] or "").strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        elif yaml_value(value) != value:
            problems.append(f"frontmatter value of '{key}' contains YAML special characters and must be quoted")
        if key in fields:
            problems.append(f"duplicate frontmatter key '{key}'")
        fields[key] = value
    return fields, problems


def describe(path: Path) -> tuple[str, str]:
    fields, _ = parse_frontmatter(read_text(path))
    fields = fields or {}
    return fields.get("title") or path.stem, fields.get("description", "")


# --- index generation --------------------------------------------------------


def entry(title: str, link: str, description: str) -> str:
    return f"- [{title}]({link})" + (f" — {description}" if description else "")


def topic_indexes() -> list[Path]:
    topics = ROOT / TOPICS_DIR
    if not topics.is_dir():
        return []
    return sorted(p for p in topics.rglob(INDEX_FILE) if not is_skipped(p.relative_to(topics)))


def render_contents(index: Path) -> str:
    folder = index.parent
    lines = []
    for sub in sorted(p for p in folder.iterdir() if p.is_dir() and (p / INDEX_FILE).is_file()):
        lines.append(entry(*_titled(sub / INDEX_FILE, f"{sub.name}/{INDEX_FILE}")))
    for file in sorted(p for p in folder.glob("*.md") if p.name != INDEX_FILE):
        lines.append(entry(*_titled(file, file.name)))
    body = "\n".join(lines) if lines else "_No files yet._"
    return f"{BEGIN_MARKER}\n## Contents\n\n{body}\n{END_MARKER}"


def _titled(path: Path, link: str) -> tuple[str, str, str]:
    title, description = describe(path)
    return title, link, description


def with_contents(text: str, block: str) -> str:
    start, end = text.find(BEGIN_PREFIX), text.find(END_MARKER)
    if start == -1 or end < start:
        return text.rstrip("\n") + "\n\n" + block + "\n"
    return text[:start] + block + text[end + len(END_MARKER):]


def render_root_index(config: dict) -> str:
    topics = ROOT / TOPICS_DIR
    lines = []
    if topics.is_dir():
        for folder in sorted(p for p in topics.iterdir() if p.is_dir() and (p / INDEX_FILE).is_file()):
            lines.append(entry(*_titled(folder / INDEX_FILE, f"{TOPICS_DIR}/{folder.name}/{INDEX_FILE}")))
    body = "\n".join(lines) if lines else "_No topics yet._"
    parts = [ROOT_INDEX_NOTICE, f"# {config.get('name', 'Knowledge Base')}"]
    if config.get("description"):
        parts.append(config["description"])
    parts += [f"> **Agents:** read [{GUIDE_FILE}]({GUIDE_FILE}) first.", f"## Topics\n\n{body}"]
    return "\n\n".join(parts) + "\n"


def expected_indexes(config: dict) -> dict[Path, str]:
    expected = {ROOT / INDEX_FILE: render_root_index(config)}
    for index in topic_indexes():
        expected[index] = with_contents(read_text(index), render_contents(index))
    return expected


def write_indexes(config: dict) -> list[str]:
    changed = []
    for path, text in expected_indexes(config).items():
        if not path.is_file() or read_text(path) != text:
            write_text(path, text)
            changed.append(rel(path))
    return changed


def cmd_index(args: argparse.Namespace) -> int:
    changed = write_indexes(load_config())
    print("Updated: " + ", ".join(changed) if changed else "Indexes are up to date.")
    return 0


# --- lint --------------------------------------------------------------------


class Report:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, path: Path, message: str) -> None:
        self.errors.append(f"{rel(path)}: {message}")

    def warn(self, path: Path, message: str) -> None:
        self.warnings.append(f"{rel(path)}: {message}")


def lint_config(report: Report) -> dict | None:
    path = ROOT / CONFIG_FILE
    config = None
    try:
        config = load_toml(path)
    except (OSError, tomllib.TOMLDecodeError) as e:
        report.error(path, f"cannot read: {e}")
    if config is not None:
        required = ("name", "description") + (() if config.get("contribution") == "with-project" else ("repository",))
        for key in required:
            if not isinstance(config.get(key), str) or not config[key].strip():
                report.error(path, f"'{key}' must be a non-empty string")
        if config.get("contribution", DEFAULT_CONTRIBUTION) not in CONTRIBUTION_MODES:
            report.error(path, f"'contribution' must be one of: {', '.join(CONTRIBUTION_MODES)}")
        authors = config.get("auto_merge", {}).get("trusted_authors", [])
        if not isinstance(authors, list) or not all(isinstance(a, str) for a in authors):
            report.error(path, "'auto_merge.trusted_authors' must be a list of GitHub logins")

    path = ROOT / TEMPLATE_FILE
    try:
        meta = load_toml(path)
    except (OSError, tomllib.TOMLDecodeError) as e:
        report.error(path, f"cannot read: {e}")
    else:
        if not VERSION_RE.match(str(meta.get("version", ""))):
            report.error(path, "'version' must be MAJOR.MINOR.PATCH")
        if not isinstance(meta.get("repository"), str) or not meta["repository"].strip():
            report.error(path, "'repository' must be a git URL")
        if not isinstance(meta.get("owned"), list):
            report.error(path, "'owned' must be a list of paths")
        if not set(meta.get("standalone_only", [])) <= set(meta.get("owned", [])):
            report.error(path, "'standalone_only' must be a subset of 'owned'")
    return config


def lint_topics(report: Report) -> None:
    topics = ROOT / TOPICS_DIR
    if not topics.is_dir():
        return
    for path in sorted(topics.rglob("*")):
        relpath = path.relative_to(topics)
        if is_skipped(relpath):
            continue
        if path.is_dir():
            if not NAME_RE.match(path.name):
                report.error(path, "folder names must be lowercase kebab-case")
            if not (path / INDEX_FILE).is_file() and (len(relpath.parts) == 1 or any(path.glob("*.md"))):
                report.error(path, f"topic folder needs an {INDEX_FILE}")
            continue
        if len(relpath.parts) == 1:
            report.error(path, f"files belong into a topic folder: {TOPICS_DIR}/<topic>/")
        try:
            text = read_text(path)
        except UnicodeDecodeError:
            continue  # binary asset
        for name, pattern in SECRET_PATTERNS.items():
            if pattern.search(text):
                report.error(path, f"possible {name} found - never store secrets")
        if path.suffix == ".md":
            lint_markdown(report, path, text)


def lint_markdown(report: Report, path: Path, text: str) -> None:
    if not NAME_RE.match(path.stem):
        report.error(path, "file names must be lowercase kebab-case")
    fields, problems = parse_frontmatter(text)
    for problem in problems:
        report.error(path, problem)
    if fields is not None:
        for key in FRONTMATTER_KEYS:
            if not fields.get(key):
                report.error(path, f"frontmatter needs a non-empty '{key}'")
        for key in sorted(fields.keys() - set(FRONTMATTER_KEYS)):
            report.error(path, f"unknown frontmatter key '{key}' (allowed: {', '.join(FRONTMATTER_KEYS)})")
        if len(fields.get("description", "")) > DESCRIPTION_CHARS_WARN:
            report.warn(path, f"description longer than {DESCRIPTION_CHARS_WARN} characters")

    lines = text.count("\n") + 1
    if path.name == INDEX_FILE:
        start, end = text.find(BEGIN_PREFIX), text.find(END_MARKER)
        if start == -1 or end < start:
            report.error(path, f"generated contents block missing: run `{INDEX_COMMAND}`")
        else:
            lines -= text[start:end].count("\n") + 1
        if lines > INDEX_LINES_WARN:
            report.warn(path, f"{lines} hand-written lines; keep entry points under {INDEX_LINES_WARN}, move details into files")
        link = guide_link(path.parent)
        if f"]({link})" not in text:
            report.error(path, f"must link to the agent guide: > **Agents:** read [the knowledge base guide]({link}) first.")
    elif lines > FILE_LINES_MAX:
        report.error(path, f"{lines} lines (max {FILE_LINES_MAX}): split into smaller files or a subfolder")
    elif lines > FILE_LINES_WARN:
        report.warn(path, f"{lines} lines: consider splitting (error above {FILE_LINES_MAX})")
    if re.search(r"\bTODO\b", text):
        report.warn(path, "contains TODO")


def markdown_files() -> list[Path]:
    files = []
    for folder, dirs, names in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        files += [Path(folder) / n for n in names if n.endswith(".md")]
    return sorted(files)


def lint_links(report: Report, path: Path, boundary: Path) -> None:
    """Relative links must resolve inside `boundary`: the repository, including project files when embedded."""
    for target in LINK_RE.findall(STRIP_RE.sub("", read_text(path))):
        if not target or target.startswith("#") or re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target):
            continue
        if target.startswith("/"):
            report.error(path, f"use relative links: {target}")
            continue
        resolved = (path.parent / urllib.parse.unquote(target.split("#")[0].split("?")[0])).resolve()
        if not resolved.is_relative_to(boundary):
            report.error(path, f"link points outside the repository: {target}")
        elif not resolved.exists():
            report.error(path, f"broken link: {target}")


def cmd_lint(args: argparse.Namespace) -> int:
    report = Report()
    config = lint_config(report)
    lint_topics(report)
    boundary = git_toplevel(ROOT) or ROOT
    for path in markdown_files():
        lint_links(report, path, boundary)
    if config is not None:
        for path, text in expected_indexes(config).items():
            if not path.is_file() or read_text(path) != text:
                report.error(path, f"index is out of date: run `{INDEX_COMMAND}`")
    for warning in report.warnings:
        print(f"warning: {warning}")
    for error in report.errors:
        print(f"error: {error}")
    print(f"{len(report.errors)} error(s), {len(report.warnings)} warning(s).")
    return 1 if report.errors else 0


# --- new-topic ---------------------------------------------------------------


TOPIC_TODO = ("TODO: 2-5 sentences: what this topic covers and when an agent needs it. "
              "Then the most important facts and gotchas, if any.")


def create_topic(path: str, title: str, description: str, overview: str = TOPIC_TODO) -> Path:
    parts = path.strip("/").split("/")
    if not all(NAME_RE.match(p) for p in parts):
        fail("topic path segments must be lowercase kebab-case, e.g. billing-api or billing-api/webhooks")
    folder = ROOT / TOPICS_DIR / Path(*parts)
    if folder.exists():
        fail(f"{rel(folder)} already exists")
    if len(parts) > 1 and not (folder.parent / INDEX_FILE).is_file():
        fail(f"parent topic {rel(folder.parent)} does not exist")
    write_text(folder / INDEX_FILE, (
        f"---\ntitle: {yaml_value(title)}\ndescription: {yaml_value(description)}\n---\n\n"
        f"> **Agents:** read [the knowledge base guide]({guide_link(folder)}) first.\n\n"
        f"# {title}\n\n{overview}\n"
    ))
    return folder / INDEX_FILE


def cmd_new_topic(args: argparse.Namespace) -> int:
    index = create_topic(args.path, args.title, args.description)
    write_indexes(load_config())
    print(f"Created {rel(index)}. Replace the TODO with an overview.")
    return 0


# --- install / init ----------------------------------------------------------

CONFIG_TEMPLATE = """\
# Configuration of this knowledge base. Owned by the knowledge base; template upgrades never touch it.

name = {name}
description = {description}
repository = {repository}

# How agents publish changes:
#   "pull-request" - pull requests; auto-merged for trusted_authors (GitHub), otherwise reviewed
#   "direct-push"  - push to main; the git server's access rights decide who may write
#   "with-project" - embedded in a project repository; changes go with the project's own commits
contribution = {contribution}

[auto_merge]
# Only for contribution = "pull-request": GitHub logins whose pull requests are merged
# automatically when lint passes and only files under topics/ or index.md change.
trusted_authors = [{authors}]
"""

README_TEMPLATE = """\
# {name}

{description}

A knowledge base for AI agents (Claude Code, GitHub Copilot), created from
[agent-knowledge-template]({template}). Agents read it to solve tasks that need knowledge
outside their training data, and keep it up to date themselves.

## Usage

Tell an agent, for example:

> Use the knowledge base {repository}, topic TOPIC. Read its AGENTS.md first.
{usage_extra}
All topics are listed in [index.md](index.md). Rules for agents: [AGENTS.md](AGENTS.md).

## Maintenance

- **New topic:** ask an agent working in a clone of this repository to create it.
{maintenance}"""

README_GITHUB = {
    "usage": "\nOr share the link to a topic entry point: {repository}/blob/main/topics/TOPIC/index.md\n",
    "pull-request": (
        "- **Changes:** pull requests by `trusted_authors` (see `knowledge-base.toml`) that only change\n"
        "  topics are merged automatically once checks pass. Everything else needs a review.\n"
    ),
    "updates": (
        "- **Template updates:** a weekly workflow opens an issue when a new template version is available.\n"
        "  Assign it to an agent (e.g. Copilot) or ask an agent to follow `.knowledge-base/UPGRADE.md`.\n"
    ),
}
README_GENERIC = {
    "pull-request": "- **Changes:** agents open pull requests; review and merge them.\n",
    "direct-push": (
        "- **Changes:** agents push topic changes directly to `main`; the git server's access rights decide\n"
        "  who may write. Other changes (tooling, template upgrades) arrive as branches to review and merge.\n"
    ),
    "updates": (
        "- **Template updates:** agents mention new template versions when they contribute. To upgrade,\n"
        "  ask an agent to follow `.knowledge-base/UPGRADE.md`.\n"
    ),
}

README_EMBEDDED = """\
# {name}

{description}

Knowledge for AI agents (Claude Code, GitHub Copilot) working on this project, created from
[agent-knowledge-template]({template}). Agents read it when a task needs knowledge that is not
evident from the code, and update it together with their code changes, so it is reviewed with them.

- Topics: [index.md](index.md). Rules for agents: [AGENTS.md](AGENTS.md).
- New topic: ask an agent to create it.
- Template updates: agents mention new template versions when they contribute. To upgrade,
  ask an agent to follow `.knowledge-base/UPGRADE.md`.
"""

# Starter topics of embedded knowledge bases: what was decided, and what had to be learned.
STARTER_TOPICS = {
    "project": (
        "Project",
        "Architecture, decisions and conventions of this project, with their reasons.",
        "What has been decided for this project - by the user or by agents, in chat or during implementation - "
        "and why: architecture, decisions, conventions. Record the outcome (what, why, rejected alternatives), "
        "not the discussion, and only what the code does not show. One file per subject; a subject that grows "
        "can become a topic of its own.",
    ),
    "learnings": (
        "Learnings",
        "Knowledge acquired while working on this project - external systems, tools, environment, workarounds.",
        "Knowledge that had to be learned to solve tasks - through questions to the user, research, or trial "
        "and error. Record the working solution and the gotchas. Knowledge useful beyond this project belongs "
        "in a shared knowledge base; link it from here. One file per subject.",
    ),
}

EMBEDDED_NEXT_STEPS = """
Embedded in a project. Next steps (see .knowledge-base/INIT.md):

1. With the user's consent, add to the project's AGENTS.md or CLAUDE.md (replace an existing
   "## Agent knowledge" section):

## Agent knowledge

Project knowledge for AI agents lives in `{prefix}/` (topics: `{prefix}/index.md`); consult it when a task touches a listed topic.
Record knowledge there when a decision or convention is made (in chat or implementation), or when you had to learn something through questions, research or trial and error.
Read `{prefix}/AGENTS.md` before using or updating it.

2. If the project has CI, offer to add a lint step (Python >= 3.11):

python {prefix}/.knowledge-base/manage.py lint
"""


def detect_repository() -> str | None:
    result = subprocess.run(["git", "remote", "get-url", "origin"], cwd=ROOT, capture_output=True, text=True)
    return result.stdout.strip() or None if result.returncode == 0 else None


def template_files(root: Path) -> list[str]:
    files = []
    for folder, dirs, names in os.walk(root):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        files += [(Path(folder) / n).relative_to(root).as_posix() for n in names if not n.endswith(".pyc")]
    return sorted(files)


def owned_matches(root: Path, pattern: str) -> list[Path]:
    if pattern.endswith("/"):
        path = root / pattern.rstrip("/")
        return [path] if path.exists() else []
    return sorted(root.glob(pattern))


def owned_files(root: Path, pattern: str) -> set[str]:
    files = set()
    for path in owned_matches(root, pattern):
        paths = [p for p in path.rglob("*") if p.is_file()] if path.is_dir() else [path]
        files |= {p.relative_to(root).as_posix() for p in paths}
    return files


def cmd_install(args: argparse.Namespace) -> int:
    source, target = ROOT, Path(args.target).resolve()
    if target.is_relative_to(source) or source.is_relative_to(target):
        fail("clone the template outside the target and run its manage.py with --target <path>")
    if (target / CONFIG_FILE).exists():
        fail(f"{target} already contains a knowledge base; use `upgrade` instead")
    embedded = is_embedded(target)
    meta = load_toml(source / TEMPLATE_FILE)
    skip = {"LICENSE"} if embedded else set()  # an embedded knowledge base falls under the project's license
    if embedded:
        for pattern in meta.get("standalone_only", []):
            skip |= owned_files(source, pattern)
    files = [f for f in template_files(source) if f not in skip]
    conflicts = [f for f in files if (target / f).exists() and f not in KEEP_IF_EXISTS and f != "README.md"]
    if conflicts and not args.force:
        fail("target already contains: " + ", ".join(conflicts) + " (use --force to overwrite)")
    for f in files:
        if f in KEEP_IF_EXISTS and (target / f).exists():
            continue
        (target / f).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / f, target / f)
    print(f"Copied template {meta['version']} to {target}" + (" (embedded in a project)." if embedded else "."), flush=True)

    command = [sys.executable, str(target / ".knowledge-base" / "manage.py"), "init",
               "--name", args.name, "--description", args.description]
    if args.repository:
        command += ["--repository", args.repository]
    if args.contribution:
        command += ["--contribution", args.contribution]
    for author in args.trusted_author or []:
        command += ["--trusted-author", author]
    return subprocess.run(command).returncode


def cmd_init(args: argparse.Namespace) -> int:
    config = load_config()
    if not config.get("is_template") and not args.force:
        fail("this knowledge base is already initialized (use --force to re-initialize)")
    embedded = is_embedded(ROOT)
    repository = args.repository or detect_repository() or ""
    if not repository and not embedded:
        fail("cannot determine the repository URL from `git remote get-url origin`; pass --repository <url>")
    slug = github_slug(repository)
    if slug:
        repository = f"https://github.com/{slug}"
    contribution = args.contribution or ("with-project" if embedded else "pull-request" if slug else "direct-push")
    authors = args.trusted_author or ([slug.split("/")[0]] if slug and contribution == "pull-request" else [])
    template = load_toml(ROOT / TEMPLATE_FILE)["repository"]

    write_text(ROOT / CONFIG_FILE, CONFIG_TEMPLATE.format(
        name=json.dumps(args.name, ensure_ascii=False),
        description=json.dumps(args.description, ensure_ascii=False),
        repository=json.dumps(repository),
        contribution=json.dumps(contribution),
        authors=", ".join(json.dumps(a) for a in authors),
    ))
    if embedded:
        readme = README_EMBEDDED.format(name=args.name, description=args.description, template=template)
        (ROOT / "LICENSE").unlink(missing_ok=True)
    else:
        github = slug is not None
        texts = README_GITHUB if github and contribution == "pull-request" else README_GENERIC
        readme = README_TEMPLATE.format(
            name=args.name, description=args.description, repository=repository, template=template,
            usage_extra=README_GITHUB["usage"].format(repository=repository) if github else "",
            maintenance=texts.get(contribution, "") + (README_GITHUB if github else README_GENERIC)["updates"],
        )
    write_text(ROOT / "README.md", readme)
    shutil.rmtree(ROOT / TOPICS_DIR / EXAMPLE_TOPIC, ignore_errors=True)
    write_indexes(load_config())
    print(f"Initialized knowledge base '{args.name}'" + (f" for {repository}" if repository else "")
          + f" (contribution: {contribution}" + (f", trusted authors: {', '.join(authors)}" if authors else "") + ").")
    if embedded:
        cmd_embed(args)
    return 0


def cmd_embed(args: argparse.Namespace) -> int:
    """Idempotent setup for embedded knowledge bases: missing starter topics, pointer for the project."""
    top = git_toplevel(ROOT)
    if top is None or top == ROOT:
        fail("this knowledge base is not embedded in a project")
    created = [rel(create_topic(slug, *texts)) for slug, texts in STARTER_TOPICS.items()
               if not (ROOT / TOPICS_DIR / slug).exists()]
    write_indexes(load_config())
    if created:
        print("Created starter topics: " + ", ".join(created))
    print(EMBEDDED_NEXT_STEPS.format(prefix=ROOT.relative_to(top).as_posix()))
    return 0


# --- upgrade -----------------------------------------------------------------


def migrations_between(text: str, old: tuple[int, ...], new: tuple[int, ...]) -> list[str]:
    sections = []
    for section in re.split(r"^## ", text, flags=re.M)[1:]:
        version = section.split(maxsplit=1)[0]
        if VERSION_RE.match(version) and old < parse_version(version) <= new:
            sections.append((parse_version(version), "## " + section.strip()))
    return [text for _, text in sorted(sections)]


def remove(path: Path, target: Path) -> None:
    """Delete an owned path and any folders it leaves empty, never touching `target` itself."""
    if path.resolve() == target or not path.resolve().is_relative_to(target):
        fail(f"refusing to delete {path}")
    shutil.rmtree(path) if path.is_dir() else path.unlink()
    parent = path.parent
    while parent.resolve() != target and parent.is_dir() and not any(parent.iterdir()):
        parent.rmdir()
        parent = parent.parent


def cmd_upgrade(args: argparse.Namespace) -> int:
    source, target = ROOT, Path(args.target).resolve()
    if source == target:
        fail("run the manage.py of the NEW template checkout with --target pointing to the knowledge base")
    if not (target / CONFIG_FILE).is_file():
        fail(f"{target} is not a knowledge base ({CONFIG_FILE} missing)")
    new_meta = load_toml(source / TEMPLATE_FILE)
    old_meta = load_toml(target / TEMPLATE_FILE) if (target / TEMPLATE_FILE).is_file() else {}
    old, new = parse_version(old_meta.get("version", "0.0.0")), parse_version(new_meta["version"])
    if new <= old and not args.force:
        print(f"Already at template version {old_meta['version']}; nothing to do.")
        return 0
    embedded = is_embedded(target)
    skipped = set(new_meta.get("standalone_only", [])) if embedded else set()

    for pattern in dict.fromkeys(old_meta.get("owned", []) + new_meta["owned"]):
        for path in owned_matches(target, pattern):
            remove(path, target)
    for pattern in new_meta["owned"]:
        if pattern in skipped:
            continue
        for path in owned_matches(source, pattern):
            destination = target / path.relative_to(source)
            if path.is_dir():
                shutil.copytree(path, destination, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, destination)

    print(f"Replaced template-owned files: {old_meta.get('version', 'unknown')} -> {new_meta['version']}"
          + (" (embedded: skipped " + ", ".join(sorted(skipped)) + ")." if skipped else "."))
    migrations = migrations_between(read_text(source / MIGRATIONS_FILE), old, new)
    print("\nApply these migration steps, oldest first:\n" if migrations else "\nNo migration steps.")
    print("\n\n".join(migrations))
    print(f"\nThen run `{INDEX_COMMAND}` and `python .knowledge-base/manage.py lint` in the knowledge base.")
    return 0


# --- template updates and pull request automation ----------------------------


def latest_template_version(repository: str) -> str:
    """Highest vMAJOR.MINOR.PATCH tag of the template; works with any git server."""
    refs = git("ls-remote", "--tags", "--refs", repository)
    versions = [m[1] for m in VERSION_TAG_RE.finditer(refs)]
    if not versions:
        fail(f"no version tags (vMAJOR.MINOR.PATCH) found in {repository}")
    return max(versions, key=parse_version)


def cmd_check_template(args: argparse.Namespace) -> int:
    meta = load_toml(ROOT / TEMPLATE_FILE)
    latest = latest_template_version(meta["repository"])
    current = meta["version"]
    available = parse_version(latest) > parse_version(current)
    status = "update available, see .knowledge-base/UPGRADE.md" if available else "up to date"
    print(f"Template {meta['repository']}: current {current}, latest {latest} ({status}).")
    set_github_output(current=current, latest=latest, update_available=str(available).lower())
    return 0


def cmd_can_auto_merge(args: argparse.Namespace) -> int:
    # Read the config from the base branch so a pull request cannot add its own author.
    config = tomllib.loads(git("show", f"{args.base}:{CONFIG_FILE}"))
    trusted = {a.lower() for a in config.get("auto_merge", {}).get("trusted_authors", [])}
    changed = git("diff", "--name-only", "--no-renames", f"{args.base}...HEAD").splitlines()
    outside = [p for p in changed if not any(p == a or (a.endswith("/") and p.startswith(a)) for a in AUTO_MERGE_PATHS)]

    reasons = []
    if args.author.lower() not in trusted:
        reasons.append(f"author '{args.author}' is not in auto_merge.trusted_authors")
    if not changed:
        reasons.append("no changed files")
    if outside:
        reasons.append("changes outside topics/ and index.md: " + ", ".join(outside))
    eligible = not reasons
    print("Eligible for auto-merge." if eligible else "Not eligible for auto-merge: " + "; ".join(reasons))
    set_github_output(eligible=str(eligible).lower())
    return 0


# --- main --------------------------------------------------------------------


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(errors="replace")
    parser = argparse.ArgumentParser(prog="manage.py", description="Knowledge base tooling.")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("index", help="regenerate index.md and the contents blocks of all topic indexes").set_defaults(func=cmd_index)
    sub.add_parser("lint", help="check structure, frontmatter, links, sizes, secrets and indexes").set_defaults(func=cmd_lint)

    p = sub.add_parser("new-topic", help="create a topic (or subtopic) folder with an index.md")
    p.add_argument("path", help="topic slug, e.g. billing-api, or billing-api/webhooks for a subtopic")
    p.add_argument("--title", required=True)
    p.add_argument("--description", required=True, help="one line: what the topic covers")
    p.set_defaults(func=cmd_new_topic)

    def add_setup_arguments(p: argparse.ArgumentParser) -> None:
        p.add_argument("--name", required=True)
        p.add_argument("--description", required=True, help="one sentence: purpose of the knowledge base")
        p.add_argument("--repository", help="git URL (default: from git remote origin)")
        p.add_argument("--contribution", choices=CONTRIBUTION_MODES,
                       help="how agents publish changes (default: with-project when embedded in a project, "
                            "pull-request on GitHub, otherwise direct-push)")
        p.add_argument("--trusted-author", action="append",
                       help="GitHub login for auto-merge in pull-request mode (repeatable; default: repo owner)")

    p = sub.add_parser("install", help="run from a template checkout: set up a knowledge base in --target "
                                       "(repository root, or a folder inside a project)")
    p.add_argument("--target", required=True, help="folder for the knowledge base, e.g. . or agent-knowledge")
    add_setup_arguments(p)
    p.add_argument("--force", action="store_true", help="overwrite existing files in the target")
    p.set_defaults(func=cmd_install)

    p = sub.add_parser("init", help="turn a copy of the template (e.g. from 'Use this template') into a knowledge base")
    add_setup_arguments(p)
    p.add_argument("--force", action="store_true", help="re-initialize an existing knowledge base")
    p.set_defaults(func=cmd_init)

    sub.add_parser("embed", help="embedded knowledge bases: create missing starter topics, print the pointer "
                                 "for the project's agent instructions (idempotent)").set_defaults(func=cmd_embed)

    p = sub.add_parser("upgrade", help="run from a NEW template checkout: replace template-owned files in --target")
    p.add_argument("--target", required=True, help="path of the knowledge base to upgrade")
    p.add_argument("--force", action="store_true", help="copy files even if the version is not newer")
    p.set_defaults(func=cmd_upgrade)

    sub.add_parser("check-template", help="compare the template version with the latest version tag of the template").set_defaults(func=cmd_check_template)

    p = sub.add_parser("can-auto-merge", help="decide whether the current pull request may be merged automatically")
    p.add_argument("--author", required=True)
    p.add_argument("--base", required=True, help="base revision, e.g. origin/main")
    p.set_defaults(func=cmd_can_auto_merge)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
